#!/usr/bin/env python3


# todo Will eventually kill this script as pyobo will be a lib, rather than a tool

import sys

sys.path.append('../')
sys.path.append('./')

from pyobo.obo_reader import read

if __name__ == "__main__":
    print(read((line for line in [
        "format-version: 1.2",
        "another-format-version: 1.3",
        "[Term]",
        "id: some term",
        "[Typedef]",
        "id: some typedef",

    ])))
